# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Filtering_Operators' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Filtering_Operators
    pod 'RxSwift', '5.1.1'
    pod 'RxRelay', '5.1.1'
end
