# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ch02_Observable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'
  # Pods for Ch02_Observable

end
