# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ch03_Subjects' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ch03_Subjects
  pod 'RxSwift', '~>5.1'
  pod 'RxRelay', '~>5.1'
end
